### ISSUE TITLE
No branch called Artifact_Evaluation

### ISSUE THREAD

**Issue by Mr-brillianter** [BinPRE/BinPRE#2]
There is no such a branch called Artifact_Evaluation and as so no install-prefix bash scripts. In your commit message, there seems a branch merge. But in README, it says
`git checkout Artifact_Evaluation
./install_preliminary.sh`
so manual install and install by docker will both fail.

**Comment by jyjsunny** [comment]
Thanks for your valuable feedback.
We have updated our README to fix that issue.
