### ISSUE TITLE
How to test a new protocol?

### ISSUE THREAD

**Issue by Fo01** [BinPRE/BinPRE#4]
Thanks for your excellent work and we have already reproduced on our machine.
However, we have focused that your paper implement many protocols, and we have a little question about how to implement them except MODBUS.
In the README file, we need to "By default, the BinPRE/src directory contains a binary file that implements the Modbus protocol, which we provide. Additionally, users are supported to add instructions into the Dockerfile to install other protocol implementations. When you install using the Dockerfile, the implementations for all these protocols will be automatically installed in the ~/BinPRE/src directory." But how can we add more instructions into the Docker file to install?
Thanks for your work again and we are looking forward to your early reply. If the text cannot explain, you can also email me at zhangyixuan@iie.ac.cn

**Comment by jyjsunny** [comment]
Thanks for your question. Similar to MODBUS, users could reverse engineering other protocol implementations by following these three steps: 

First, install server by 1) adding corresponding instructions into the Docker file, or 2)manually installing them into the directory `./BinPRE/src`.
Second, modify related configuration information. (i.e., `./Analyzer/config.py`)
Third, construct ground-truth with the specification. 

If you would like to reproduce our evaluation on more protocols, please check the **full version** paper of BinPRE https://arxiv.org/pdf/2409.01994 to find more details of the benchmark.

Please feel free to modify the Dockerfile and running scripts according to the projects you would like to test.
